repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        include: \.py$  # Include only Python files
      - id: end-of-file-fixer
        include: \.py$  # Include only Python files
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        include: \.py$  # Include only Python files
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        include: \.py$  # Include only Python files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-requests]
