create table
  public.books (
    id bigint generated by default as identity,
    title character varying null,
    type character varying null,
    status character varying null,
    description text null,
    cover_url character varying null,
    release smallint null,
    constraint book_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.chapters (
    id bigint generated by default as identity,
    number real null,
    book_id bigint null,
    release date null,
    constraint chapter_pkey primary key (id),
    constraint chapter_book_id_fkey foreign key (book_id) references books (id)
  ) tablespace pg_default;

create table
  public.images (
    id bigint generated by default as identity,
    number integer null,
    url character varying null default ''::character varying,
    chapter_id bigint null,
    constraint Image_pkey primary key (id),
    constraint image_chapter_id_fkey foreign key (chapter_id) references chapters (id)
  ) tablespace pg_default;

create table
  public.genres (
    id bigint generated by default as identity,
    name character varying null default ''::character varying,
    constraint Genre_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.book_genres (
    book_id bigint not null,
    genre_id bigint not null,
    constraint book_genres_pkey primary key (book_id, genre_id),
    constraint book_genre_book_id_fkey foreign key (book_id) references books (id),
    constraint book_genre_genre_id_fkey foreign key (genre_id) references genres (id)
  ) tablespace pg_default;

create table
  public.book_authors (
    author_id bigint not null,
    book_id bigint not null,
    constraint book_authors_pkey primary key (author_id, book_id),
    constraint book_author_author_id_fkey foreign key (author_id) references authors (id),
    constraint book_author_book_id_fkey foreign key (book_id) references books (id)
  ) tablespace pg_default;

create table
  public.authors (
    id bigint generated by default as identity,
    first_name character varying null default ''::character varying,
    last_name character varying null default ''::character varying,
    constraint Author_pkey primary key (id)
  ) tablespace pg_default;
